# Generated by Django 4.0.7 on 2022-08-18 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('debate_id', models.AutoField(primary_key=True, serialize=False)),
                ('debate_topic', models.CharField(max_length=50)),
                ('debate_description', models.TextField(default='')),
                ('debate_keywords', models.CharField(max_length=50)),
                ('debate_start_date', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 16, 33, 9, 321570))),
                ('debate_end_date', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 19, 33, 9, 321570))),
            ],
        ),
        migrations.CreateModel(
            name='DebateActor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
